# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTotalcart():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_cart_total(self):
        # Test name: cart_total
        # Step # | name | target | value
        # 1 | open | /en/ |
        self.driver.get("https://prestashop-ta26.multibit.ro/en/")
        # 2 | setWindowSize | 1168x643 |
        self.driver.set_window_size(1168, 643)
        # 3 | click | css=.js-product:nth-child(4) img |
        self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(4) img").click()
        # 4 | click | css=.touchspin-up |
        self.driver.find_element(By.CSS_SELECTOR, ".touchspin-up").click()
        # 5 | click | css=.add-to-cart |
        self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
        # 6 | click | css=.cart-content-btn > .btn-primary |
        item = WebDriverWait(self.driver, 10).until(lambda driver:driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary"))
        item.click()
        # 7 | click | css=.cart-total > .value |
        self.driver.find_element(By.CSS_SELECTOR, ".cart-total > .value").click()
        # 8 | assertText | css=.cart-total > .value | lei69.02
        assert self.driver.find_element(By.CSS_SELECTOR, ".cart-total > .value").text == "lei69.02"
