# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddblack():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addblack(self):
    # Test name: add_black
    # Step # | name | target | value
    # 1 | open | /en/ | 
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    # 2 | setWindowSize | 1168x643 | 
    self.driver.set_window_size(1168, 643)
    # 3 | click | css=.js-product:nth-child(1) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(1) img").click()
    # 4 | click | css=.float-xs-left:nth-child(2) .input-color | 
    self.driver.find_element(By.CSS_SELECTOR, ".float-xs-left:nth-child(2) .input-color").click()
    # 5 | click | css=.add-to-cart |
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 6 | click | css=.cart-content-btn > .btn-primary |
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary").click()
    # 7 | click | css=.color > .value |
    self.driver.find_element(By.CSS_SELECTOR, ".color > .value").click()
    # 8 | assertText | css=.color > .value | Black
    assert self.driver.find_element(By.CSS_SELECTOR, ".color > .value").text == "Black"
  
