# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddtocart2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addtocart2(self):
    # Test name: add_to_cart2
    # Step # | name | target | value
    # 1 | open | https://prestashop-ta26.multibit.ro/en/ | 
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    # 2 | setWindowSize | 1167x634 | 
    self.driver.set_window_size(1167, 634)
    # 3 | click | css=.js-product:nth-child(3) img | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(3) img").click()
    # 4 | click | css=.add-to-cart |
    product_name = self.driver.find_element(By.TAG_NAME, "h1").get_attribute("innerText")
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    # 5 | click | css=.cart-content-btn > .btn-primary |
    element = WebDriverWait(self.driver, 10).until(lambda driver:driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary"))
    element.click()
    assert product_name.lower() in self.driver.page_source.lower()
  
