# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAddpostertocart():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_addpostertocart(self):
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    self.driver.set_window_size(1168, 635)
    self.driver.find_element(By.CSS_SELECTOR, ".js-product:nth-child(4) img").click()
    product_name = self.driver.find_element(By.TAG_NAME, "h1").get_attribute("innerText")
    self.driver.find_element(By.CSS_SELECTOR, ".add-to-cart").click()
    element = WebDriverWait(self.driver,15).until(lambda driver:driver.find_element(By.CSS_SELECTOR, ".cart-content-btn > .btn-primary"))
    element.click()
    assert product_name.upper() in self.driver.page_source.upper()