# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestContactus():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_contactus(self):
    # Test name: contact_us
    # Step # | name | target | value
    # 1 | open | https://prestashop-ta26.multibit.ro/en/ | 
    self.driver.get("https://prestashop-ta26.multibit.ro/en/")
    # 2 | setWindowSize | 1168x639 | 
    self.driver.set_window_size(1168, 639)
    # 3 | click | linkText=Contact us | 
    self.driver.find_element(By.LINK_TEXT, "Contact us").click()
    # # 4 | click | id=id_contact |
    # self.driver.find_element(By.ID, "id_contact").click()
    # 6 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 9 | type | id=email | lucaciubogdansorin@gmail.com
    self.driver.find_element(By.ID, "email").send_keys("lucaciubogdansorin@gmail.com")
    # 10 | click | id=contactform-message | 
    self.driver.find_element(By.ID, "contactform-message").click()
    # 11 | type | id=contactform-message | help!
    self.driver.find_element(By.ID, "contactform-message").send_keys("help!")
    # 12 | click | name=submitMessage | 
    self.driver.find_element(By.NAME, "submitMessage").click()
    # 13 | mouseOver | name=submitDateYearPrev |
    # Test name: Untitled
    # Step # | name | target | value
    # 1 | open | https://prestashop-ta26.multibit.ro/admin619cii23r/index.php?controller=AdminLogin&logout=1&token=0727cac84b756b82f5a456fad085a128 |
    self.driver.get(
      "https://prestashop-ta26.multibit.ro/admin619cii23r/index.php?controller=AdminLogin&logout=1&token=0727cac84b756b82f5a456fad085a128")
    # 2 | setWindowSize | 1168x641 |
    self.driver.set_window_size(1168, 641)
    # 3 | type | id=passwd | TestatareAutomata26
    self.driver.find_element(By.ID, "passwd").send_keys("TestatareAutomata26")
    # 4 | type | id=email | ta26@multibit.ro
    self.driver.find_element(By.ID, "email").send_keys("ta26@multibit.ro")
    # 5 | click | css=.ladda-label |
    self.driver.find_element(By.CSS_SELECTOR, ".ladda-label").click()
    # 6 | click | css=#subtab-AdminParentCustomerThreads span |
    self.driver.implicitly_wait(10)
    self.driver.find_element(By.CSS_SELECTOR, "#subtab-AdminParentCustomerThreads span").click()
    # 7 | click | linkText=Customer Service |
    self.driver.find_element(By.LINK_TEXT, "Customer Service").click()
    # 8 | runScript | window.scrollTo(0,0) |
    self.driver.execute_script("window.scrollTo(0,0)")
    # 9 | click | css=.odd > .column-email |
    self.driver.find_element(By.CSS_SELECTOR, ".odd > .column-email").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".message-item-text").text == "help!"

